Builds on pr #78 to further add a split DNS provider for Systemd-resolved
dlenski/vpn-slice pull request #118
Opened 2022-09-08 08:14 UTC by fuero

Adds a split DNS provider for Systemd-resolved.

Uses a slightly changed version of PR #78

2022-09-09 14:01 UTC, gmacon requested changes
It's been some time since I looked at the previous PR, so I just reviewed this anew. It looks reasonable overall, but I have some comments. One top-level comment: please update README to mention the new systemd-resolved support.

Thanks for your effort putting this together.

2022-09-11 21:13 UTC, fuero commented on vpn_slice/__main__.py
> +            ResolvedSplitDNSProvider = None
I've changed `inuse` to a class method.

2022-09-11 21:14 UTC, fuero commented on vpn_slice/linux.py
> +        pprint(cl)
Missed removing that one, sorry - changed this to a `logging.debug` call as you suggested.

2022-09-11 21:16 UTC, fuero commented on vpn_slice/linux.py
> +            self._resolvectl(*([ 'dns', tundev ] + [ str(x).encode('utf-8') for x in nameservers ]))
I looked a little too much at the other code than to actually think about what I was writing. `format(x)` should be good then?

2022-09-15 23:44 UTC, gmacon requested changes

2022-09-15 23:44 UTC, gmacon commented on vpn_slice/__main__.py
> +            ResolvedSplitDNSProvider = None
I guess I should explicitly have said "and you therefore need to call it", since that was the underlying cause of my original comment :-)

2022-09-16 14:35 UTC, fuero commented
@gmacon
Ok, so I hopefully got it right this time - sorry for needing to spoonfeed me this. I've omitted the lines I used in testing this to set up python logging, if you are interested I can add this in another PR and change the various print statements to logging.* calls.

2022-09-17 22:28 UTC, gmacon approved these changes
This looks good to me. I don't think changing the logging framework belongs in this PR, so you can leave that as-is for now. I'll let this sit for a day or so to see if there are any last-minute comments from other people and then merge it.

2022-09-19 01:36 UTC, merged

2023-07-06 19:04 UTC, dlenski commented
Hi @fuero and @gmacon, I've started using (and paying attention to :sweat_smile:) `vpn-slice` for the first time in a while.

This PR was a very good effort to add split-DNS support on Linux, but it seems not to have been tested on systems where *neither of those* is in use (see 9703bce49e0996f43dba2e4fcc295bceb06ebdb5, for one example of what goes wrong).

For the time being, I've *reverted* this PR, and I've moved it to a branch called https://github.com/dlenski/vpn-slice/commits/Linux_split_DNS_PR118_rework, which contains some additional code simplification and cleanup on top of what was merged in this PR.

I'll try to get it back into mainline-able shape when I have time, but also feel free to resubmit it if you're motivated to do that work!

2023-07-10 10:39 UTC, madushan1000 commented
@dlenski there is a bug in [Linux_split_DNS_PR118_rework](https://github.com/dlenski/vpn-slice/compare/Linux_split_DNS_PR118_rework). The script will not assign correct dns servers to the tun interface when using `ResolvedSplitDNSProvider` because `subprocess.check_call([self.resolvectl, 'dns', tundev] + nameservers)
` will produce(on python 3.11) a command like `resolvectl dns tun0 IPv4Address('0.0.0.0') IPv4Address('1.1.1.1')`.
So it should be changed to something like `subprocess.check_call([self.resolvectl, 'dns', tundev] + [str(i) for i in nameservers])`